"""The assessment as a document somebody can file.

PS11 capability 10 asks for a written report. A web page is not one: hiring
decisions get forwarded, argued about six weeks later, and attached to
paperwork, and none of that works with a URL behind a login that renders
whatever the database says today. A PDF is a fixed record of what was known
when the decision was made.

RENDERED SERVER-SIDE, with WeasyPrint. The alternative was a print stylesheet
and asking the operator to use their browser's Save as PDF, which produces a
different document on every machine, silently drops backgrounds by default, and
cannot be generated by anything except a human at a keyboard — no emailing it,
no attaching it to an ATS, no scripting it.

TWO RULES THIS DOCUMENT KEEPS, both inherited from the rest of the product:

  * EVERY MARK CARRIES ITS QUOTE. A number a hiring manager cannot see the
    reason for is not evidence. The quotes were verified against the transcript
    when they were scored, so nothing here can cite something unsaid.

  * WHAT WAS NOT MEASURED IS SAID OUT LOUD. A thin interview, a missing round,
    monitoring that was not running — each is printed as plainly as the score
    is. A report that only shows what it knows reads as though it knows
    everything.

The full transcript goes at the back, numbered, so every quote above can be
found in context rather than taken on trust.
"""

import html
import logging
from datetime import datetime

log = logging.getLogger("report")

# Print CSS, not screen CSS. Points rather than pixels, a real page box, and
# `break-inside: avoid` on anything whose halves would be meaningless apart —
# an evidence quote split across a page boundary loses the mark it justifies.
STYLE = """
@page {
  size: A4;
  margin: 18mm 16mm 20mm;
  @bottom-center {
    content: "Page " counter(page) " of " counter(pages);
    font: 8pt "DejaVu Sans", sans-serif; color: #8a8f9e;
  }
}
* { box-sizing: border-box; }
body {
  font: 10pt/1.5 "DejaVu Sans", sans-serif;
  color: #191b2c; margin: 0;
}
h1 { font-size: 21pt; margin: 0 0 2mm; letter-spacing: -.4pt; }
h2 {
  font-size: 12pt; margin: 9mm 0 3mm; padding-bottom: 1.6mm;
  border-bottom: .5pt solid #d6d9e3; letter-spacing: -.2pt;
}
h3 { font-size: 10pt; margin: 5mm 0 1.5mm; }
p  { margin: 0 0 2mm; }
.muted { color: #666c85; }
.small { font-size: 8.5pt; }

.masthead {
  border-bottom: 2pt solid #f2542d; padding-bottom: 4mm; margin-bottom: 6mm;
}
.masthead .who { font-size: 11pt; margin-top: 1mm; }
.masthead .meta { font-size: 8.5pt; color: #666c85; margin-top: 2mm; }

.verdict {
  display: block; margin: 4mm 0 0; padding: 3mm 4mm;
  border-left: 3pt solid #f2542d; background: #faf7f5;
}
.verdict .big { font-size: 24pt; font-weight: bold; letter-spacing: -1pt; }
.verdict .of  { font-size: 9pt; color: #666c85; }

table { width: 100%; border-collapse: collapse; margin-top: 2mm; }
th, td {
  text-align: left; padding: 1.8mm 2mm; font-size: 9pt;
  border-bottom: .5pt solid #e6e8f0; vertical-align: top;
}
th { font-size: 7.5pt; text-transform: uppercase; letter-spacing: .4pt; color: #666c85; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }

.evidence { break-inside: avoid; margin-bottom: 3.5mm; }
.evidence .turnref {
  font-size: 7.5pt; color: #666c85; text-transform: uppercase; letter-spacing: .4pt;
}
.evidence .concept { font-weight: bold; font-size: 9.5pt; }
.evidence .quote {
  border-left: 2pt solid #f2542d; padding: .5mm 0 .5mm 3mm;
  margin-top: 1mm; font-style: italic; color: #3a3d52;
}

.flag { break-inside: avoid; margin-bottom: 3.5mm; padding-left: 3mm;
        border-left: 2pt solid #c0392b; }
.flag .kind { font-weight: bold; font-size: 9.5pt; }
.flag .quote { font-style: italic; color: #3a3d52; margin-top: .8mm; }

.signal { break-inside: avoid; margin-bottom: 3mm; }
.signal .caveat { color: #666c85; font-size: 8.5pt; }

.note {
  background: #f3f4f8; padding: 3mm 4mm; margin: 3mm 0; font-size: 9pt;
  border-radius: 2pt;
}
.note.warn { background: #fdf6e9; border-left: 2pt solid #9a6414; }

.turn { break-inside: avoid; margin-bottom: 2.5mm; }
.turn .speaker {
  font-size: 7.5pt; text-transform: uppercase; letter-spacing: .4pt;
  color: #666c85;
}
.turn.candidate { padding-left: 4mm; border-left: 1.5pt solid #e6e8f0; }
.transcript { page-break-before: always; }
.footnote {
  margin-top: 8mm; padding-top: 3mm; border-top: .5pt solid #d6d9e3;
  font-size: 8pt; color: #666c85;
}
"""


def _e(value) -> str:
    """Escape for HTML, and print a zero as a zero.

    `str(value or "")` looks equivalent and is not: 0 is falsy, so a candidate
    with no forks, no followers or no flags got a blank cell instead of a
    number — which reads as missing data rather than as none.
    """
    return html.escape("" if value is None else str(value))


def _pct(value) -> str:
    return "—" if value is None else f"{round(value * 100)}%"


def _marks(assessment: dict) -> str:
    by_role = assessment.get("by_role") or {}
    if not by_role:
        return ""
    rows = "".join(
        f"<tr><td>{_e(role.replace('_', ' ').title())}</td>"
        f"<td class='num'>{m.get('earned', 0):.1f}</td>"
        f"<td class='num'>{m.get('available', 0):.1f}</td>"
        f"<td class='num'>{round(m.get('fraction', 0) * 100)}%</td></tr>"
        for role, m in by_role.items()
    )
    return (
        "<h2>Marks by interviewer</h2>"
        "<table><tr><th>Interviewer</th><th class='num'>Earned</th>"
        "<th class='num'>Available</th><th class='num'>Share</th></tr>"
        f"{rows}</table>"
    )


def _basis(assessment: dict) -> str:
    """What the score was measured on — printed next to it, never below it.

    Both numbers that make a percentage comparable between two candidates:
    how many questions they actually answered, and how many marks the
    questions they were asked were worth. Difficulty scales marks without
    being renormalised, so `available` above 100 means the ladder pushed them
    into harder questions.
    """
    answers = assessment.get("answers", 0)
    available = assessment.get("available", 0)
    nominal = assessment.get("total", 100)
    thin = answers and answers < 4

    warn = (
        f"<div class='note warn'><b>Read this before comparing.</b> "
        f"{answers} answered question{'s' if answers != 1 else ''} is a small "
        f"sample rather than a measurement — one weak turn moves the "
        f"percentage a long way. Read the transcript.</div>"
        if thin else ""
    )
    return (
        "<h2>What this was measured on</h2>"
        "<table>"
        f"<tr><td>Questions answered</td><td class='num'>{_e(answers)}</td></tr>"
        f"<tr><td>Marks available on the questions asked</td>"
        f"<td class='num'>{available:.0f}</td></tr>"
        f"<tr><td>Nominal total for any interview</td>"
        f"<td class='num'>{nominal:.0f}</td></tr>"
        "</table>"
        "<p class='small muted'>Marks available differs from the nominal total "
        "because harder questions carry more marks and easier ones fewer. That "
        "is deliberate: it is what stops a candidate who was pushed onto hard "
        "questions being ranked below one who was not.</p>"
        f"{warn}"
    )


def _evidence(assessment: dict) -> str:
    items = assessment.get("evidence") or []
    if not items:
        return ("<h2>Evidence</h2><p class='muted'>No concepts were recorded "
                "as covered.</p>")
    body = "".join(
        f"<div class='evidence'>"
        f"<div class='turnref'>Turn {_e(e.get('turn_id'))} · "
        f"{_e(str(e.get('role', '')).replace('_', ' '))}</div>"
        f"<div class='concept'>{_e(e.get('concept'))}</div>"
        f"<div class='quote'>“{_e(e.get('quote'))}”</div>"
        f"</div>"
        for e in items
    )
    return (
        "<h2>Evidence</h2>"
        "<p class='small muted'>Every mark awarded, with the candidate's own "
        "words that earned it. Each quote was checked against the transcript "
        "at the moment it was scored, so nothing here cites something "
        "unsaid.</p>"
        f"{body}"
    )


def _flags(assessment: dict) -> str:
    items = assessment.get("flags") or []
    if not items:
        return ""

    def one(f: dict) -> str:
        kind = str(f.get("kind", "")).replace("_", " ")
        quotes = ""
        if f.get("quote"):
            quotes += f"<div class='quote'>Earlier: “{_e(f['quote'])}”</div>"
        if f.get("quote_b"):
            quotes += f"<div class='quote'>Later: “{_e(f['quote_b'])}”</div>"
        ref = (f" · against turn {_e(f['ref_turn_id'])}"
               if f.get("ref_turn_id") else "")
        return (
            f"<div class='flag'>"
            f"<div class='turnref'>Turn {_e(f.get('turn_id'))}{ref} · "
            f"raised by the {_e(f.get('source') or 'panel')}</div>"
            f"<div class='kind'>{_e(kind)}</div>"
            f"<p class='small'>{_e(f.get('detail'))}</p>{quotes}</div>"
        )

    return (
        "<h2>Flags</h2>"
        "<p class='small muted'>Raised either by the instant check during the "
        "conversation or by the model judge afterwards. A contradiction is "
        "shown with both statements so it can be checked rather than "
        "believed.</p>"
        + "".join(one(f) for f in items)
    )


def _integrity(integrity: dict) -> str:
    if not integrity:
        return ""
    if not integrity.get("monitored"):
        return (
            "<h2>Integrity</h2>"
            f"<div class='note'>{_e(integrity.get('note'))}</div>"
        )

    coverage = integrity.get("coverage") or {}
    gap = ""
    if not coverage.get("complete"):
        gap = (
            "<div class='note warn'><b>Monitoring was not running for the "
            f"whole interview</b> — roughly {round(coverage.get('gap_seconds', 0))} "
            "seconds went unwatched. That is missing data, not a clean "
            "record.</div>"
        )

    signals = "".join(
        f"<div class='signal'><b>{_e(s['label'])}</b> — {s['count']}×"
        + (f", {round(s['seconds'])}s total" if s.get("seconds", 0) >= 1 else "")
        + f"<p class='small'>{_e(s['means'])}</p>"
        f"<p class='caveat'><b>But:</b> {_e(s['but'])}</p></div>"
        for s in integrity.get("signals", [])
    ) or "<p class='muted'>Nothing was flagged.</p>"

    return (
        "<h2>Integrity</h2>"
        f"<p class='small muted'>{_e(integrity.get('headline'))}</p>"
        f"{gap}{signals}"
        f"<div class='note'>{_e(integrity.get('note'))}</div>"
    )


def _profile(profile: dict) -> str:
    github = (profile or {}).get("github")
    linkedin = (profile or {}).get("linkedin_url")
    if not github and not linkedin:
        return ""

    parts = ["<h2>Candidate profile</h2>"]
    if github:
        proven = (github.get("ownership") or {}).get("proven")
        p, a = github.get("profile", {}), github.get("activity", {})
        parts.append(
            f"<p><b>github.com/{_e(github.get('username'))}</b> — "
            f"{'ownership proven' if proven else 'CLAIMED, not proven'}</p>"
        )
        if not proven:
            parts.append(
                "<div class='note warn'>The candidate entered this username; "
                "nobody has proven the account is theirs. Read it as a "
                "claim.</div>"
            )
        parts.append(
            "<table>"
            f"<tr><td>Account age</td><td class='num'>{_e(p.get('age_years'))} yrs</td></tr>"
            f"<tr><td>Public repositories</td><td class='num'>{_e(p.get('public_repos'))}</td></tr>"
            f"<tr><td>Own / forked</td><td class='num'>{_e(a.get('original'))} / {_e(a.get('forks'))}</td></tr>"
            f"<tr><td>Pushed to this year</td><td class='num'>{_e(a.get('pushed_last_year'))}</td></tr>"
            "</table>"
        )
        match = github.get("resume_match") or {}
        if match.get("available"):
            backed = ", ".join(c["language"] for c in match.get("corroborated", []))
            claimed = ", ".join(match.get("claimed_not_seen", []))
            if backed:
                parts.append(f"<p class='small'><b>Backed by public code:</b> {_e(backed)}</p>")
            if claimed:
                parts.append(f"<p class='small'><b>On the CV, no public repo:</b> {_e(claimed)}</p>")
            parts.append(f"<p class='small muted'>{_e(match.get('note'))}</p>")

    if linkedin:
        parts.append(
            f"<p class='small'><b>LinkedIn:</b> {_e(linkedin)} — a link the "
            "candidate supplied. Nothing has checked it: LinkedIn has no "
            "public API and its terms prohibit scraping.</p>"
        )
    return "".join(parts)


def _transcript(turns: list) -> str:
    if not turns:
        return ""
    body = "".join(
        "<div class='turn {}'><div class='speaker'>[{}] {}</div><p>{}</p></div>".format(
            "candidate" if t.get("speaker") == "candidate" else "",
            _e(t.get("turn_id")),
            _e("Candidate" if t.get("speaker") == "candidate"
               else str(t.get("speaker", "")).replace("_", " ").title()),
            _e(t.get("text")),
        )
        for t in turns
    )
    return (
        "<div class='transcript'><h2>Full transcript</h2>"
        "<p class='small muted'>Every quote above can be found here in "
        f"context. {len(turns)} turns.</p>{body}</div>"
    )


DECISION_LABEL = {"hire": "Hire", "no_hire": "No hire", "maybe": "Maybe"}


def build_html(report: dict) -> str:
    """The whole document, as one self-contained HTML string."""
    assessment = report.get("assessment") or {}
    candidate = (report.get("candidate_profile") or {}).get("full_name") \
        or report.get("candidate") or "Candidate"
    when = datetime.now().strftime("%d %B %Y")

    decision = report.get("decision")
    decision_block = (
        f"<div class='note'><b>Recorded decision: "
        f"{_e(DECISION_LABEL.get(decision, decision))}</b> — made by a person, "
        "not by the panel.</div>"
        if decision else
        "<div class='note'>No hiring decision has been recorded yet. The panel "
        "assesses; a person decides.</div>"
    )

    if assessment:
        verdict = (
            "<div class='verdict'>"
            f"<span class='big'>{_pct(assessment.get('fraction'))}</span> "
            f"<span class='of'>&nbsp;{assessment.get('earned', 0):.1f} of "
            f"{assessment.get('total', 0):.0f} marks"
            + (f", {assessment.get('penalties', 0):.1f} deducted for vague or "
               "contradictory answers" if assessment.get("penalties", 0) else "")
            + "</span></div>"
        )
        body = (
            verdict + decision_block + _basis(assessment) + _marks(assessment)
            + _flags(assessment) + _evidence(assessment)
        )
    else:
        body = (
            "<div class='note warn'><b>This interview was not marked.</b> "
            f"{_e(report.get('note'))}</div>" + decision_block
        )

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Assessment — {_e(candidate)}</title>
<style>{STYLE}</style></head><body>
<div class="masthead">
  <h1>Interview assessment</h1>
  <div class="who"><b>{_e(candidate)}</b> — {_e(report.get('job_title') or 'Interview')}</div>
  <div class="meta">
    Interview {_e(report.get('session_id'))} · generated {when} ·
    conducted by an AI panel, assessed against a rubric written before each
    answer was given
  </div>
</div>
{body}
{_profile(report.get('candidate_profile'))}
{_integrity(report.get('integrity'))}
{_transcript(report.get('transcript'))}
<div class="footnote">
  Every interviewer on this panel was an AI, and the candidate was told so out
  loud before the interview began. Scores come from a marking scheme written
  when each question was asked — before the answer existed — and every mark
  cites a quote verified against the transcript above. Integrity signals carry
  no marks. The hiring decision is a person's, and is recorded with their name
  and the time they made it.
</div>
</body></html>"""


def build_pdf(report: dict) -> bytes:
    """Render the document. Raises if WeasyPrint is unavailable.

    Imported inside the function on purpose: WeasyPrint pulls in the system
    Pango and Cairo libraries at import time, and a machine without them should
    fail when somebody asks for a PDF — not when the gateway starts and every
    interview stops working.
    """
    from weasyprint import HTML

    return HTML(string=build_html(report)).write_pdf()


def filename(report: dict) -> str:
    who = ((report.get("candidate_profile") or {}).get("full_name")
           or report.get("session_id") or "assessment")
    safe = "".join(c if c.isalnum() or c in "-_ " else "" for c in str(who)).strip()
    return f"{(safe or 'assessment').replace(' ', '-')}-assessment.pdf"
